//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_MVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MEHSULLAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MEHSULLAR()
        {
            this.TBL_SATISLAR = new HashSet<TBL_SATISLAR>();
        }
    
        public int MEHSULID { get; set; }
        public string MEHSULAD { get; set; }
        public string MARKA { get; set; }
        public Nullable<int> MEHSULKATEQORIYA { get; set; }
        public Nullable<decimal> QIYMET { get; set; }
        public Nullable<byte> STOK { get; set; }
    
        public virtual TBL_KATEQORIYALAR TBL_KATEQORIYALAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SATISLAR> TBL_SATISLAR { get; set; }
    }
}
